# Generated by Django 3.2.20 on 2023-09-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='answers',
            field=models.ManyToManyField(blank=True, null=True, to='quiz.ChoiceExplanation'),
        ),
    ]
