# Generated by Django 3.2.20 on 2023-09-19 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_quizquestion_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.year'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='answers',
            field=models.ManyToManyField(blank=True, to='quiz.ChoiceExplanation'),
        ),
    ]
