# Generated by Django 3.2.20 on 2023-09-19 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20230919_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='year',
        ),
    ]
