# Generated by Django 3.2.21 on 2023-09-23 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.field'),
        ),
    ]
