# Generated by Django 3.2.21 on 2023-09-26 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20230926_1013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='the_order',
        ),
    ]
