# Generated by Django 3.2.21 on 2023-09-26 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20230926_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='level',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='tree_id',
        ),
    ]
