# Generated by Django 3.2.21 on 2023-09-26 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_auto_20230927_0142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subject',
            new_name='grade',
        ),
    ]
