# Generated by Django 3.2.21 on 2023-09-26 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_rename_subject_subject_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='grade',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
