# Generated by Django 3.2.21 on 2023-09-26 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_grade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
