# Generated by Django 3.2.21 on 2023-09-26 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_auto_20230927_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='grade',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
