# Generated by Django 3.2.21 on 2023-09-26 17:43

import adminsortable.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_auto_20230927_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('the_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'ordering': ['the_order'],
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='grade',
            field=adminsortable.fields.SortableForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.grade'),
            preserve_default=False,
        ),
    ]
