# Generated by Django 3.2.21 on 2023-09-29 02:33

import adminsortable.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_auto_20230927_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='field',
            field=adminsortable.fields.SortableForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.field'),
        ),
    ]
