# Generated by Django 3.2.21 on 2023-10-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_alter_quizquestion_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='question_text',
            field=models.CharField(max_length=1000),
        ),
    ]
